// <auto-generated />
using System;
using Final_project.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Final_project.Migrations
{
    [DbContext(typeof(SushinContext))]
    partial class SushinContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Final_project.Domain.Entity.Sushi", b =>
                {
                    b.Property<Guid>("_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<decimal>("_Coast")
                        .HasColumnType("numeric(38,17)")
                        .HasColumnName("Coast");

                    b.Property<string>("_Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("_Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<int>("_Number")
                        .HasColumnType("int")
                        .HasColumnName("Number");

                    b.HasKey("_Id")
                        .HasName("Id");

                    b.ToTable("Sushi", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
